### ISSUE TITLE
Feature: User can add a username

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users that visit this application will be able to input a username of their choice.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There will be an input section where a user is allowed to type in a string. This string should have a conditional where a minimum of 7 characters is typed into this section. Only then, is the username a valid input.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:

![image](https://user-images.githubusercontent.com/113082803/209991040-01936b15-5cb8-492c-b0ab-7958faea183a.png)

Desktop: 

![image](https://user-images.githubusercontent.com/113082803/209991127-703c9113-098d-499b-a2bb-99ebca372564.png)
![image](https://user-images.githubusercontent.com/113082803/209991184-b2c2081c-6453-48b8-ac8a-8b02bbe02c6a.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Import tables from database designer into `schema.sql`.
- [x] Add sample data to the `users` table inside of `data.sql`.
- [x] Update `data.sql` to ... Insert a new username into the users table.

### ☁️ Server Tasks

- [x] Edit `GET` request to retrieve data from the `users` table and test out in terminal.
- [x] Update `server/index.js` to send a POST request to create a new username in the users table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new component named `username.jsx`.
- [x] Create a class `NewUserName` into the new component.
- [x] Create and render a mockup in this file to replicate the directions, input field, and a `next` button.
- [x] Add a constructor, super, and `this.state={isClicked: false}`.
- [x] After the constructor, add a `handleclick` function with no parameter and bind to `this`.
- [x] Create a `handleUserName` function with `event` as a parameter and bind to `this`.
- [x] Create a `handleSubmitUserName` function with `event` as a parameter and bind to `this`.
- [x] Add `event.preventDefault()` to the beginning of the submit listener and set the `userName` back to an empty string to reset the input.
- [x] Add `this.handleClick` to the button, `handleUserName` to the input and `handleSubmitUserName` to the `form` element. then use console logs to ensure they are functional with no error.
- [x] Add if statement `if the field is clicked on and the username is less than 7 characters`, user cannot move forward.
- [x] If the input is valid, make a conditional that sets a success text to click next.
- [x] Add a console log to the submit form to check whether a valid username was submitted.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
