### ISSUE TITLE
Feature: User can scroll through history of messages

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can scroll through chatroom to see previous messages.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

As more messages are being sent to the chatroom, the page will become larger. The user should be able to scroll inside the conversation box when there are a lot of messages to view its history of messages.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:

![image](https://user-images.githubusercontent.com/113082803/209864411-6e54673c-d9be-4c8a-8dc9-8a3d95f029db.png)

Desktop:

![image](https://user-images.githubusercontent.com/113082803/209864300-3f298ec1-782c-4a9a-a1e4-0e5eb7c35b89.png)
![image](https://user-images.githubusercontent.com/113082803/209864319-24d22c6f-b7ea-4f47-abb2-dd29ad3f8995.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Go to `chat-container.jsx` and try to set dimensions for the chat section.
- [x] Add a background color to the div to match the wireframe.
- [x] Style the div to appear wider when on desktop view.
- [x] Test with multiple messages to ensure that a scroll is available inside the chat.
- [x] Try to refactor the `send-msg.jsx` component to be displayed at the bottom of the screen.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
