### ISSUE TITLE
Feature: User can choose a chat room to join

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to choose a chat room to enter.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There should be a React component that is displayed after a user clicks on the `next` button. On this component, should be a modal prompting the user to select a room from a dropdown list. Within this list will be premade room names that can be selected.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile: 

![image](https://user-images.githubusercontent.com/113082803/209854646-3bb42511-236e-4bad-ab9b-c29991687762.png)

Desktop: 

![image](https://user-images.githubusercontent.com/113082803/209854841-3ebdfd0c-7d46-46a7-8a87-dcd378719954.png)
![image](https://user-images.githubusercontent.com/113082803/209854869-ac3c4a12-078b-4540-9eea-492b3654d4c5.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to insert data for `chatRoom`.
- [x] Add `sql` variable that retrieves data from the `chatRoom` table.

### ☁️ Server Tasks

- [x] Make sure that previous http requests are working fine.
- [x] Make a new `GET` request that prints out the list of chat rooms.
- [x] Make a new `POST` request that updates the `usersInChat` to include a `userId` and `roomId` & test in terminal.
- [x] Make sure that `usersInChat` updates when a user selects a room and clicks `next`.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component named `room-select.jsx`.
- [x] For now, export default a new function named `SelectRoom` and import into `home.jsx`.
- [x] In the `SelectRoom` component, create a mockup of the wireframe for a room selection.
- [x] Create hash route for the `next` button on the `username.jsx` component and make sure views swap properly.
- [x] Change the function to a class and add the constructor, super and `this.state`.
- [x] Use console logs to make sure the select element is being clicked and the option value is logged per click target.
- [x] Set a conditional if the user does not select a room, a user cannot move forward.
- [x] If a room is selected, display a success message.
- [x] Use console logs to test whether rooms are being clicked and selected properly.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
