### ISSUE TITLE
Feature nine: User can edit a message

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#22]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can update their message in the chat room.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On each chat messages that is populated in the chat, there should be an edit icon that appears when a user hovers over their message. This should only be applicable to messages sent by a specific user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:

![image](https://user-images.githubusercontent.com/113082803/209860371-dd551e7c-e915-486f-b51b-0b47fa192148.png)

Desktop:

![image](https://user-images.githubusercontent.com/113082803/209860238-1f2632cc-82c5-4060-b017-bfc9cec75b76.png)
![image](https://user-images.githubusercontent.com/113082803/209860268-97329ef6-50c8-48b6-9513-48ee862a652d.png)
![image](https://user-images.githubusercontent.com/113082803/209860287-6cf9e07f-5703-4e6c-9226-9df698cdea47.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Go to `server/index.js` and add a `PATCH` request.
- [ ] Make sure that the input MUST be a positive integer that is greater than 0.
- [ ] Test this request by modifying a message that was sent from the client.

### ⚡ Client Tasks

- [ ] Create a component `edit-modal.jsx` in the *chat-container* directory.
- [ ] Create a mockup modal that will look like the wireframe.
- [ ] Create a conditional that will open this modal when the target message is selected.
- [ ] Add functionality for a `PATCH` request.
- [ ] Make sure the client side updates the message in the database.
- [ ] Make sure the message is updated on the client side.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
