### ISSUE TITLE
Feature: User can hear a chime when a new user joins or leaves

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can hear an audible chime when a new user enters the room or leaves the room.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After a user selects a chat room and clicks on `next`, there should be a `play sound` in the React component for the `next` button. When clicked on, the play function should trigger the audio source. When functionality for 'leave chat room' is implemented, this feature should also be implemented when a user leaves.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile: 
![image](https://user-images.githubusercontent.com/113082803/209855395-21bb27f0-df7f-445e-84e0-4b69372def37.png)

Desktop:

![image](https://user-images.githubusercontent.com/113082803/209855480-bebe0680-009d-4388-a703-10e48fd5ff28.png)
![image](https://user-images.githubusercontent.com/113082803/209855535-67a8c1a5-c482-4dab-bd03-29912e4e893a.png)
![image](https://user-images.githubusercontent.com/113082803/209855554-68b1439f-6698-4108-b8cf-5f68d5374f20.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a "parent" component: `chat-room.jsx` with 3 "children" components: `room-name`, `chat-box`, and `sender` and render a `<p>TEST</p>` to make sure imports are correct.
- [x] Create mock ups for each child component to mock the wireframes.
- [x] In the `Sender` component, make sure that the values change when users click and type the input box.
- [x] Go back to the component `room-select.jsx` and add a hash route that directs user to the "chat room".
- [x] Insert chime audio file into the `server/public` directory.
- [x] Add a play sound function that plays once when a user selects a room and joins in.
- [x] Run a test to make sure an audio is played upon entering chat.
- [x] Upon entering a chat, all incoming users should generate a message.
- [x] Along with the enter message, make sure a timestamp is generated on the side.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
