### ISSUE TITLE
Feature 10: User can scroll to bottom of the page

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#30]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Add the React Hook `UseRef` in `chat-container`.
- [x] Add an empty div to the bottom of the chat container holding messages.
- [x] Create a new variable named `newest` and set the `useRef` to `null`.
- [x] Define a new function `latestMsg` to scroll into view with smooth transition.
- [x] Pass the callback function into `ChatBoxReceiver` and call it in the useState.
- [x] Test that the auto scroll works on new message.
- [x] Add an anchor tag that will allow user to jump to the bottom of new message.
- [x] Add a click listener to this anchor for the callback function `latestMsg`.
- [x] Test that this function works.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
