### ISSUE TITLE
Feature: User can send messages to another user

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users that enter a chat room can both send a message to one another.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A component for a text box should always be present. All users should be able to click on the box and type a message. When they finish the message, the send button should also be clickable and make a POST request to the server and print the message on both user's screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:

![image](https://user-images.githubusercontent.com/113082803/209857149-f833729a-a7c1-4f65-8ec0-99b6039c1955.png)

Desktop: 

![image](https://user-images.githubusercontent.com/113082803/209856802-53a961a4-5684-4ad2-886b-4233fd27b834.png)
![image](https://user-images.githubusercontent.com/113082803/209856839-15f8cdf7-0d8d-4689-b941-8cedd513675f.png)
![image](https://user-images.githubusercontent.com/113082803/209856931-6a539d3d-6c5b-47ec-a686-1bfacf43778f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `messages` in the `schema.sql` to have a column for `sentByUserId` and a `timestamp`.
- [x] Update `data.sql` to upload sample data for a message.

### ☁️ Server Tasks

- [x] Install dependencies: `socket.io`, `socket.io-client`.
- [x] Go to `index.js` and require `socket.io`, `http`, and `socketEvents`.
- [x] Create a listener for the socket.
- [x] Create a socket server, middleware, and server routes.
- [x] Update `server/index.js` to make a `POST` request to upload each message typed into the `messages` table.
- [x] Test the `POST` request with a new message that was sent by a user.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add a new file in client/lib named `io.js`, import `io from 'socket.io-client'`, and create an environment variable.
- [x] Make a fetch request in the `submit` event to `POST` a message to the `messages` table.
- [x] Implement socket.io in the `chat-container.jsx` and `chat-box.jsx` components.
- [x] Update the `chat-container.jsx` component to fetch a `POST` request which will save the typed message into the `messages` table in the database.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
