### ISSUE TITLE
Feature: User can see a timestamp of when message was sent

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the timestamp of a message.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a message is posted, the time at which it was created should be attached to the message box so that all users in the chat room can see.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:

![image](https://user-images.githubusercontent.com/113082803/209857149-f833729a-a7c1-4f65-8ec0-99b6039c1955.png)

Desktop: 

![image](https://user-images.githubusercontent.com/113082803/209856802-53a961a4-5684-4ad2-886b-4233fd27b834.png)
![image](https://user-images.githubusercontent.com/113082803/209856839-15f8cdf7-0d8d-4689-b941-8cedd513675f.png)
![image](https://user-images.githubusercontent.com/113082803/209856931-6a539d3d-6c5b-47ec-a686-1bfacf43778f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to `GET` the timestamp of the latest message that was sent.
- [x] Test this `GET` request and make sure that the timestamp is correct.
- [x] Convert the timestamp from GMT to PST.
- [x] Update `server/index.js` to `POST` a user entering a chat room in `usersInChat` table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Go to the `username.jsx` component and modify/add a fetch request to `POST` to `usersInChat` table in database.
- [x] Make sure that as soon as a user enters the chat room, the `usersInChat` table will be updated. 
- [x] Go to the `chat-box.jsx` component and add a test timestamp to `messages` in the receiver and sender functions.
- [x] Send messages as sender and receiver to test and add styling as needed.
- [x] Add a function that will fetch for the timestamp from database.
- [x] Make sure that the timestamp is being fetched properly by console logging the data.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
