### ISSUE TITLE
Feature: User can receive notifications

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can see a popup towards the bottom of the screen when a new message was generated.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After a user sends a message to the chat room, all other users will receive a popup which will serve as a visual alert that a new message was received in the chat room. This should only apply to all users except for the sender.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:

![image](https://user-images.githubusercontent.com/113082803/209857938-2e511c55-3419-49da-95a9-5cb64cc53aa6.png)

Desktop:

![image](https://user-images.githubusercontent.com/113082803/209857975-3b76efaf-b677-4ed6-b643-3244215b8901.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Install `react-toastify` and make sure it's a dependency in `package.json`.

### ⚡ Client Tasks

- [x] Go to `chat-container.jsx` and modify the 'message box' div to a shorter `minHeight`.
- [x] Go to `send-msg.jsx` and add another div on top of the input form with a empty div.
- [x] Create an alert that looks like the wireframe for an incoming message.
- [x] Create a condition that will generate this alert when a new message is sent.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
