### ISSUE TITLE
Feature: User can hear a chime for incoming messages

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can hear an audible chime when a new message is sent from another user.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the popup notification is triggered, there should also be a `play sound` that triggers a notification sound when a new message is sent.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:

![image](https://user-images.githubusercontent.com/113082803/209857938-2e511c55-3419-49da-95a9-5cb64cc53aa6.png)

Desktop:

![image](https://user-images.githubusercontent.com/113082803/209857975-3b76efaf-b677-4ed6-b643-3244215b8901.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Insert audio file inside `../server/public` directory.
- [x] Go to `chat-box.jsx` component and import the audio file.
- [x] Create a new function in `chat-box.jsx` that will play the audio file.
- [x] Call this function in `ChatBoxReceiver` and make sure audio is played when message is sent to receiver.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
