### ISSUE TITLE
Feature Eight: User can send emojis

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send emojis using the input with commands.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user types in a specific key, the chat box will automatically render an emoji to replace the command.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [ ] Go to `chat-box.jsx` component, and create a function that will convert a ' :) ' to an emoji.
- [ ] Add a conditional that will render an emoji to the command.
- [ ] Test whether the client side will produce an emoji.
- [ ] Add more preset emojis to the function.
- [ ] Test that the emojis are properly rendering.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
