### ISSUE TITLE
Feature Nine: User can leave a chatroom

### ISSUE THREAD

**Issue by MattChau01** [MattChau01/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can leave the chatroom that they are currently in.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user would like to leave the current chatroom, there is a button available towards the top of the page. If they click on this icon, they will be prompted with a modal to confirm their choice. If they confirm, they will be led to the main screen to select another room.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile:

![image](https://user-images.githubusercontent.com/113082803/209861047-4613d403-40e3-4e76-8172-13225dbd6270.png)

Desktop:

![image](https://user-images.githubusercontent.com/113082803/209863781-5bdc6fba-d78b-4e48-aff5-eb0dbbd67120.png)
![image](https://user-images.githubusercontent.com/113082803/209863799-a6049d5d-5c13-43cb-8b5a-cf6c97eea094.png)
![image](https://user-images.githubusercontent.com/113082803/209863812-d7b27eb1-1326-4354-bc18-b7f91ca40db7.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component `modal-popup.jsx` and import into the `chat-room.jsx` component.
- [x] Create a mockup for the modal similar to the wireframe.
- [x] Add a `click` listener for the `cancel` button.
- [x] Make sure the `click` listener is working by console logging `button is clicked`.
- [x] Conditionally render the modal when the `exit` icon is clicked and closed when `cancel` is clicked.
- [x] Add a `click` listener to the `confirm` button.
- [x] Make sure the `click` listener is working by console logging `button is clicked`.
- [x] Create a function `confirmClicked`, and replace this with the console log.
- [x] In the `confirmClicked` function, use a hash route that will re-direct user to the `room-select` component.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
